### ISSUE TITLE
플로우 차트 디자인 관련

### ISSUE THREAD

**Issue by JJJangJeongSu** [vlvksbdof1234/open_source_project_team3#1]
플로우 차트를 디자인 하고 있는데 다음과 같은 개선사항이 필요할 듯
1. 로직이 복잡해지면 플로우차트 이미지 크기가 커져서 
      1) 스크롤바 필요
      2) 플로우 차트 크게보기( 팝업?)으로 띄어주기 (주변 화면 어두워지면서 ) - 뭐였는지 기억이 안나네

2. 설정 기능
     - 언어 (한글? 영어) 
     - 상세한 정도    간단 보통 상세 를 Range로 설정가능하게
     - 하단에 적용, 취소 버튼
     
![image](https://github.com/vlvksbdof1234/open_source_project_team3/assets/78810864/10d1e1b3-d6f8-401a-8828-00ae278044a3)

**Comment by vlvksbdof1234** [comment]
1. 플로우차트
i) 플로우차트를 바깥쪽을 감싸는 div내에 overflow라는 class를 지정해주면 스크롤이 가능, 다만 이미지 사이즈에 대한 명확한 명시가 필요할 것으로 예상돼
https://getbootstrap.com/docs/5.0/utilities/overflow/

ii) 플로우차트 modal을 통해서 이미지를 띄워주는게 가능
https://getbootstrap.com/docs/4.3/components/modal/

**Comment by vlvksbdof1234** [comment]
flowchart 하위에 구현 완료
