### ISSUE TITLE
React 버전 통일 관련

### ISSUE THREAD

**Issue by JJJangJeongSu** [vlvksbdof1234/open_source_project_team3#3]
React의 버전을 통일해야 할 것 같은데, 어떻게 생각하십니까

**Comment by vlvksbdof1234** [comment]
`    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"`
    
AI_code_helper/package.json에 react 버젼 명시 되어있어서 내꺼 clone해서 npm install하면 아무래도 버젼이 동일하게 맞춰질 것 같아, 그리고 수업 때에 대부분 node를 설치한 것 같아서, node 버젼도 맞을 것 같고, 그래서 react 의존성 문제는 없을 것으로 생각되긴하는데, 아마 문제있다면 문제 있는 친구의 node 버젼을 손봐야 할 것 같아.

**Comment by vlvksbdof1234** [comment]
ace code editor 지원하는 버젼이 react 16~버젼까지만 지원하는게 있어서 ace code edtior 포기하고 다른 라이브러리 사용
theme만 변경해서 작성하는걸로
